### ISSUE TITLE
internal error: entered unreachable code (defining a type with a macro)

### ISSUE THREAD

**Issue by anowell** [rust-lang-nursery/rustfmt#1209]
I encountered this error using `cargo fmt`:

```
thread 'main' panicked at 'internal error: entered unreachable code', /home/anowell/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-0.6.2/src/types.rs:598
stack backtrace:
   1:     0x5599318633b8 - std::sys::imp::backtrace::tracing::imp::write::he3d1bfbdbf113480
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55993186709f - std::panicking::default_hook::{{closure}}::h575f1b40d2e88f07
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x559931865656 - std::panicking::default_hook::h3d5dccce8125d0cf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x559931865ca7 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x55993163263f - std::panicking::begin_panic::h70ee11343cda1bc2
   6:     0x55993168944c - rustfmt::types::<impl rustfmt::rewrite::Rewrite for syntex_syntax::ast::Ty>::rewrite::h145889997323136d
   7:     0x559931683181 - <rustfmt::types::SegmentParam<'a> as rustfmt::rewrite::Rewrite>::rewrite::hb6e3658c08ecddd0
   8:     0x5599316cdf62 - <rustfmt::lists::ListItems<'a, I, F1, F2, F3> as core::iter::iterator::Iterator>::next::{{closure}}::hbcd105eaed20ad8c
   9:     0x55993165a431 - <collections::vec::Vec<T> as core::iter::traits::FromIterator<T>>::from_iter::hb71b55ce5b3ccc3c
  10:     0x55993167ebe4 - rustfmt::lists::list_helper::hb07659a98d7e6800
  11:     0x5599316840af - rustfmt::types::rewrite_segment::h4c0fca7d09a04596
  12:     0x559931682d39 - rustfmt::types::rewrite_path::h3343b99c634a1719
  13:     0x5599316876f4 - rustfmt::types::<impl rustfmt::rewrite::Rewrite for syntex_syntax::ast::Ty>::rewrite::h145889997323136d
  14:     0x5599316744d5 - rustfmt::items::<impl rustfmt::rewrite::Rewrite for syntex_syntax::ast::StructField>::rewrite::he59511d6d317e40b
  15:     0x5599316d52cf - <rustfmt::lists::ListItems<'a, I, F1, F2, F3> as core::iter::iterator::Iterator>::next::{{closure}}::h53431080bbb9d6e0
  16:     0x559931657bc7 - <collections::vec::Vec<T> as core::iter::traits::FromIterator<T>>::from_iter::h2667fbddc550b10a
  17:     0x55993167e880 - rustfmt::lists::list_helper::h6b78f5eec77138f2
  18:     0x55993167356d - rustfmt::items::format_struct::hfe6ece3d3aa960e6
  19:     0x5599316714ff - rustfmt::items::<impl rustfmt::visitor::FmtVisitor<'a>>::format_variant::hc2ad11f370274566
  20:     0x5599316ced32 - <rustfmt::lists::ListItems<'a, I, F1, F2, F3> as core::iter::iterator::Iterator>::next::{{closure}}::h1a0c179dd0bbae46
  21:     0x55993167f594 - rustfmt::lists::write_list::h311e2ed0c020cf0e
  22:     0x559931670bd1 - rustfmt::items::<impl rustfmt::visitor::FmtVisitor<'a>>::visit_enum::hdfbc97362c51f0c0
  23:     0x559931665ef3 - rustfmt::visitor::FmtVisitor::visit_item::hd7536d44408505a9
  24:     0x55993166d9b7 - rustfmt::visitor::FmtVisitor::walk_mod_items::h95937de79b8e9546
  25:     0x55993166da5e - rustfmt::visitor::FmtVisitor::format_separate_mod::hf1773fce455531d5
  26:     0x5599316ad56b - rustfmt::format_ast::hbd7b4696dd0eedd7
  27:     0x5599316b1f3c - rustfmt::run::hb0982ff25b171eaa
  28:     0x5599316251d3 - rustfmt::execute::h343cec4818a20c2b
  29:     0x559931626e1c - rustfmt::main::h6f953a4dfa5e665e
  30:     0x55993186eb7a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  31:     0x5599318663da - std::rt::lang_start::h74b3afbdd8daef1c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  32:     0x7f724bb3d290 - __libc_start_main
  33:     0x55993161efc9 - _start
  34:                0x0 - <unknown>
```

It seems related to an awkward use of a macro to conditionally define a type so that `JsonValue!()` would evaluate as `serde_json::Value` when built with serde, and `rustc-serialize::json::Json` when build with rustc-serialize. I can work around the panic by using a conditionally defined type alias instead (which is probably the better choice). This commit shows the before and after of code that hit this panic: https://github.com/anowell/algorithmia-rust/commit/78434083f9335fd4af5737278ff8e30afffb8968

**Comment by topecongiro** [comment]
We do not panic anymore, though we still do not format macros on types.
