### ISSUE TITLE
rustfmt panics on eshell

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rustfmt#1414]
When running `rustfmt (0.8.0)` against a file which does not exist from eshell (The Emacs Shell), `rustfmt` panics.

```
thread 'main' panicked at 'failed to emit error: operation not supported by the terminal', /home/topecongiro/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_errors-0.58.1/src/emitter.rs:1043
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

With backtrace:
```
thread 'main' panicked at 'failed to emit error: operation not supported by the terminal', /home/topecongiro/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_errors-0.58.1/src/emitter.rs:1043
stack backtrace:
   0:     0x55aacbf9e1a3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hf9ed9ccfd9f14c2b
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55aacbf9a5f4 - std::sys_common::backtrace::_print::hd8a1b72dcf3955ef
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x55aacbfa0167 - std::panicking::default_hook::{{closure}}::h5ff605bba7612658
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x55aacbf9fceb - std::panicking::default_hook::h9bc4f6dfee57d6bd
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x55aacbfa05db - std::panicking::rust_panic_with_hook::hdc01585dc2bf7122
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x55aacbfa04b4 - std::panicking::begin_panic::hf84f4975d9f9b642
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x55aacbfa03e9 - std::panicking::begin_panic_fmt::hcc3f360b2ba80419
                               at /checkout/src/libstd/panicking.rs:495
   7:     0x55aacbf32c37 - <syntex_errors::emitter::EmitterWriter as syntex_errors::emitter::Emitter>::emit::h37c4ed0897b06b97
   8:     0x55aacbf40e66 - syntex_errors::Handler::fatal::h727638f077d420ee
   9:     0x55aacbeefba1 - syntex_syntax::parse::file_to_filemap::h72b9f23646cbc644
  10:     0x55aacbeef93a - syntex_syntax::parse::new_parser_from_file::h64f4d720949cc67e
  11:     0x55aacbe0cb8f - rustfmt::parse_input::h7494d94df0e0055a
  12:     0x55aacbe0d48a - rustfmt::run::h009e90c17496b8d5
  13:     0x55aacbd538d7 - rustfmt::execute::h8efe604f63f81483
  14:     0x55aacbd5780a - rustfmt::main::h52e17993a988191f
  15:     0x55aacbfa02d5 - std::panicking::try::do_call::h689a21caeeef92aa
                               at /checkout/src/libcore/ops.rs:2606
                               at /checkout/src/libstd/panicking.rs:454
  16:     0x55aacbfa74ea - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  17:     0x55aacbfa0d7a - std::rt::lang_start::hf63d494cb7dd034c
                               at /checkout/src/libstd/panicking.rs:433
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:57
  18:     0x7f80fd3e8510 - __libc_start_main
  19:     0x55aacbd4f189 - _start
  20:                0x0 - <unknown>
```

**Comment by topecongiro** [comment]
I am sorry, this was a duplicate of #1180. Closing this issue.
