### ISSUE TITLE
chain_indent parsing crashes on 0.8.1

### ISSUE THREAD

**Issue by clux** [rust-lang-nursery/rustfmt#1426]
I just upgraded from 0.8.0 to 0.8.1 and found that a working config now crashes on `cargo fmt` without good info.

Here's the rustfmt.toml:

```toml
chain_base_indent = "tabbed"
chain_indent = "tabbed"
fn_arg_indent = "tabbed"
closure_block_indent_threshold = 0
single_line_if_else_max_width = 90
write_mode = "overwrite"
use_try_shorthand = true
```

OUTPUT:

```sh
Warning: Unused configuration option chain_base_indent
Warning: Unused configuration option fn_arg_indent
Decoding config file failed. Config:
chain_base_indent = "tabbed"
chain_indent = "tabbed"
fn_arg_indent = "tabbed"
closure_block_indent_threshold = 0
single_line_if_else_max_width = 90
write_mode = "overwrite"
use_try_shorthand = true



Parsed:
Table({"chain_base_indent": String("tabbed"), "chain_indent": String("tabbed"), "closure_block_indent_threshold": Integer(0), "fn_arg_indent": String("tabbed"), "single_line_if_else_max_width": Integer(90), "use_try_shorthand": Boolean(true), "write_mode": String("overwrite")})
thread 'main' panicked at 'explicit panic', /home/clux/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-0.8.1/src/config.rs:319
stack backtrace:
   1:     0x562c7934661c - std::sys::imp::backtrace::tracing::imp::write::hf33ae72d0baa11ed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x562c79348fde - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x562c79348be4 - std::panicking::default_hook::h1670459d2f3f8843
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x562c7934941b - std::panicking::rust_panic_with_hook::hcf0ddb069e7beee7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x562c79105f0f - std::panicking::begin_panic::h20af3f49d5862a29
   6:     0x562c791ab1a6 - rustfmt::config::Config::from_toml::h694c4e7d25a2fc6a
   7:     0x562c790ed090 - rustfmt::resolve_config::h99bbe5e6dd9bf8f1
   8:     0x562c790f0528 - rustfmt::execute::h2a56a4ab73659311
   9:     0x562c790f24da - rustfmt::main::h1183d24b6d57d4a5
  10:     0x562c793502aa - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  11:     0x562c79349b86 - std::rt::lang_start::hd7c880a37a646e81
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/rt.rs:57
  12:     0x7fb9165f4290 - __libc_start_main
  13:     0x562c790eae99 - _start
  14:                0x0 - <unknown>
```

This is on `rustc 1.16.0 (30cf806ef 2017-03-10)`

After some bisecting of the config it appears that the `chain_indent = "tabbed"` is what causes the crash, but that's not really identifiable by the crash.

Edit: fixed a typo.

**Comment by nrc** [comment]
That option has been removed, so this is expected. However, we should do better by giving a message rather than crashing.
