### ISSUE TITLE
panics on crate imageflow_core

### ISSUE THREAD

**Issue by nathanaeljones** [rust-lang-nursery/rustfmt#1939]
https://github.com/imazen/imageflow/tree/master/imageflow_core
```
n@nathanael-xeon:~/Documents/imazen/imageflow$ RUST_BACKTRACE=1 cargo fmt --package imageflow_core
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:49
  10: rustfmt::visitor::FmtVisitor::visit_attrs
  11: rustfmt::visitor::FmtVisitor::visit_item
  12: rustfmt::visitor::FmtVisitor::walk_mod_items
  13: rustfmt::run
  14: rustfmt::execute
  15: rustfmt::main
  16: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  17: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  18: __libc_start_main
```

**Comment by topecongiro** [comment]
Could you please try with the latest rustfmt-nightly? The issue should be solved with it.

**Comment by nrc** [comment]
Assuming this is fixed on nightly. Closing (please comment if not and I'll re-open).
