### ISSUE TITLE
cargo fmt --all panics

### ISSUE THREAD

**Issue by imp** [rust-lang-nursery/rustfmt#1963]
Running `cargo fmt --all` in the crate (whether workspaces or not) panics on unwrapping `None` value. The stack is below. It wasn't obvious what went wrong until I recompiled from source with `--debug`, so for the future it may be useful to replace those `.unwrap()` with `.expect()` to at least give some guidance on the failure.

```
$ RUST_BACKTRACE=full cargo fmt --all -- --write-mode diff
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
stack backtrace:
   0:       0xf7af95b233 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hc5a1742ed06100f7
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:       0xf7af95789a - std::sys_common::backtrace::_print::h3c1ebf2d590cb524
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:       0xf7af95e1a3 - std::panicking::default_hook::{{closure}}::h9958606e33ea2c89
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:381
   3:       0xf7af95df12 - std::panicking::default_hook::h0d4a9d88ac9dc23d
                               at /checkout/src/libstd/panicking.rs:397
   4:       0xf7af95e5a7 - std::panicking::rust_panic_with_hook::h9dc4887458447c61
                               at /checkout/src/libstd/panicking.rs:577
   5:       0xf7af95e474 - std::panicking::begin_panic::h983068f412e04c2f
                               at /checkout/src/libstd/panicking.rs:538
   6:       0xf7af95e379 - std::panicking::begin_panic_fmt::hfc0f8cca0ca0fd32
                               at /checkout/src/libstd/panicking.rs:522
   7:       0xf7af95e30a - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:498
   8:       0xf7af995410 - core::panicking::panic_fmt::h440bf49996550842
                               at /checkout/src/libcore/panicking.rs:71
   9:       0xf7af995346 - core::panicking::panic::h70a4f999a9b6fb15
                               at /checkout/src/libcore/panicking.rs:51
  10:       0xf7af8cd86a - <core::option::Option<T>>::unwrap::hd13b310bfae1925d
                               at /checkout/src/libcore/macros.rs:20
  11:       0xf7af8d4e00 - cargo_fmt::get_targets::h6b74538112b0c8ab
                               at src/bin/cargo-fmt.rs:257
  12:       0xf7af8d3d1f - cargo_fmt::format_crate::h01a1e4736e328d6e
                               at src/bin/cargo-fmt.rs:120
  13:       0xf7af8d368e - cargo_fmt::execute::h87d77fd6a519b948
                               at src/bin/cargo-fmt.rs:87
  14:       0xf7af8d2efc - cargo_fmt::main::he6086c81bcc5171a
                               at src/bin/cargo-fmt.rs:31
  15:       0xf7af9653ac - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
  16:       0xf7af95edcb - std::rt::lang_start::h81ca4cff9aa4aef6
                               at /checkout/src/libstd/panicking.rs:459
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:59
  17:       0xf7af8d6752 - main
  18:     0x7f23b3eb082f - __libc_start_main
  19:       0xf7af8bedc8 - _start
  20:                0x0 - <unknown>
```

**Comment by nrc** [comment]
What crate were you running on?

**Comment by imp** [comment]
Well I first encountered it on my own source, which is workspace, but the stack trace above is from `rustfmt` itself

**Comment by topecongiro** [comment]
FWIW this could be reproduced with am empty crate as well.
```
% cargo new foo
% cd foo
% cargo fmt --all
```
and panics.
