### ISSUE TITLE
Panic with indent_style = "Visual"

### ISSUE THREAD

**Issue by YaLTeR** [rust-lang-nursery/rustfmt#2217]
Somewhat minimal example:
```rust
fn main() {
    match engine.asdasd()
                .asdasd()
                .asdasd()
                .asdasd()
                .asdasd()
                .map(|ptr| unsafe { ptr.asdasd() }.asd()) {}
}
```
inside `src/main.rs` of a clean project.

```
thread 'main' panicked at 'Request to format inverted span: Loc { file: FileMap(/home/yalter/Source/rust/rustfmt_bug/src/main.rs), line: 7, col: CharPos(28), col_display: 28 } to Loc { file: FileMap(/home/yalter/Source/rust/rustfmt_bug/src/main.rs), line: 7, col: CharPos(27), col_display: 27 }', .cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.16/src/missed_spans.rs:68:8
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: _ZN3std9panicking12default_hook28_$u7b$$u7b$closure$u7d$$u7d$17hef59f1d15185c20fE.llvm.272A3273
             at /checkout/src/libstd/panicking.rs:381
   3: _ZN3std9panicking12default_hook17h7cc618db9a2c6232E.llvm.272A3273
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: _ZN3std9panicking11begin_panic17hd8d93c98c4fac2daE.llvm.272A3273
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rustfmt_nightly::missed_spans::<impl rustfmt_nightly::visitor::FmtVisitor<'a>>::format_missing_with_indent
   8: rustfmt_nightly::visitor::FmtVisitor::push_rewrite
   9: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  10: rustfmt_nightly::visitor::FmtVisitor::visit_block
  11: rustfmt_nightly::expr::rewrite_block_with_visitor
  12: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Block>::rewrite
  13: rustfmt_nightly::closures::rewrite_closure_block
  14: rustfmt_nightly::closures::rewrite_closure_with_block
  15: rustfmt_nightly::expr::format_expr
  16: rustfmt_nightly::expr::try_overflow_last_arg
  17: rustfmt_nightly::expr::rewrite_call_inner
  18: rustfmt_nightly::expr::rewrite_call
  19: rustfmt_nightly::chains::rewrite_chain_subexpr
  20: rustfmt_nightly::chains::rewrite_chain::{{closure}}
  21: rustfmt_nightly::chains::rewrite_chain
  22: rustfmt_nightly::expr::format_expr
  23: rustfmt_nightly::expr::format_expr
  24: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Stmt>::rewrite
  25: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  26: rustfmt_nightly::visitor::FmtVisitor::visit_block
  27: rustfmt_nightly::visitor::FmtVisitor::visit_fn
  28: rustfmt_nightly::visitor::FmtVisitor::visit_item
  29: rustfmt_nightly::visitor::FmtVisitor::walk_items
  30: rustfmt_nightly::visitor::FmtVisitor::walk_mod_items
  31: rustfmt_nightly::format_ast
  32: rustfmt_nightly::run
  33: rustfmt::execute
  34: rustfmt::main
  35: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  36: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/rt.rs:58
  37: __libc_start_main
  38: _start
```

**Comment by topecongiro** [comment]
Thank you for filing an issue! Fortunately this is already reported in #2207 and fixed on the master.

Closing as a duplicate.
