### ISSUE TITLE
C/Java style documentation comments produce bogus output and make rustfmt panic

### ISSUE THREAD

**Issue by Timvde** [rust-lang-nursery/rustfmt#2277]
```
$ rustfmt --version
0.9.0-nightly ( )
```

Given this simple file:

```Rust
/**
 * This is a C-style documentation comment.
 */
fn foo() {}
```

Running `rustfmt` once changes the file to:

```Rust
#[doc = /**
 * This is a C-style documentation comment.
 */]
fn foo() {}
```

Running rustfmt a second time produces a panic:

```
$ RUST_BACKTRACE=1 rustfmt src/lib.rs
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: rustfmt::visitor::FmtVisitor::visit_attrs
  11: rustfmt::visitor::FmtVisitor::visit_item
  12: rustfmt::visitor::FmtVisitor::walk_mod_items
  13: rustfmt::format_input
  14: rustfmt::run
  15: rustfmt::execute
  16: rustfmt::main
  17: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  18: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  19: __libc_start_main
  20: _start
```

**Comment by Timvde** [comment]
I'm sorry, I just installed `rustfmt` this weekend and didn't consider that it might not have been the latest version. `rustfmt 0.10` still shows the bug, but it suggests to use `rustfmt-nightly` instead. I'm having issues running nightly, so I can't reproduce myself:

```
rustfmt: error while loading shared libraries: libsyntax-6fd65f55af72a984.so: cannot open shared object file: No such file or directory
```

**Comment by nrc** [comment]
I'm pretty sure this is fixed on nightly, so closing. See the last [tip](https://github.com/rust-lang-nursery/rustfmt#tips) for how to avoid the shared library error.
