### ISSUE TITLE
Crash on rustfmt-nightly 0.3.5

### ISSUE THREAD

**Issue by TeXitoi** [rust-lang-nursery/rustfmt#2370]
rustfmt installed with `cargo +nightly install --force rustfmt-nightly`

```rust
fn main() {
    assert_eq!(le_clos["label"], "Lotissement le Clos de Givry (Livry-sur-Seine)");
}
```
```
$ rustup run nightly rustfmt --version
0.3.5-nightly ( )
$ RUST_BACKTRACE=1 rustup run nightly rustfmt test.rs 
thread 'main' panicked at 'slice index starts at 3 but ends at 2', libcore/slice/mod.rs:791:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::slice::slice_index_order_fail
             at libcore/slice/mod.rs:791
  10: rustfmt_nightly::expr::rewrite_call_args
  11: rustfmt_nightly::expr::rewrite_call_inner
  12: rustfmt_nightly::macros::rewrite_macro
  13: rustfmt_nightly::visitor::FmtVisitor::visit_mac
  14: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  15: rustfmt_nightly::visitor::FmtVisitor::visit_block
  16: rustfmt_nightly::visitor::FmtVisitor::visit_fn
  17: rustfmt_nightly::visitor::FmtVisitor::visit_item
  18: rustfmt_nightly::visitor::FmtVisitor::walk_items
  19: rustfmt_nightly::run
  20: rustfmt::execute
  21: rustfmt::main
  22: std::rt::lang_start::{{closure}}
  23: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  24: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  25: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  26: main
  27: __libc_start_main
  28: _start
$ 
```

**Comment by topecongiro** [comment]
@TeXitoi Thank you for filing an issue!
