### ISSUE TITLE
Slice indexing panic when trying to format encoding_rs

### ISSUE THREAD

**Issue by hsivonen** [rust-lang-nursery/rustfmt#2374]
Steps to reproduce (as of 2018-01-18):

1. `rustup default nightly`
2. `cargo install --force rustfmt-nightly`
3. `git clone https://github.com/hsivonen/encoding_rs.git`
4. `cd encoding_rs`
5. `git checkout 29fe5c7713be6cf6270cf9d9d8d55eb514161e90`
6. `RUST_BACKTRACE=1 cargo fmt`

Actual results:

```
Warning: Unknown configuration option `fn_call_style`
thread 'main' panicked at 'slice index starts at 3 but ends at 2', libcore/slice/mod.rs:791:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::slice::slice_index_order_fail
             at libcore/slice/mod.rs:791
  10: rustfmt_nightly::expr::rewrite_call_args
  11: rustfmt_nightly::expr::rewrite_call_inner
  12: rustfmt_nightly::macros::rewrite_macro
  13: rustfmt_nightly::visitor::FmtVisitor::visit_mac
  14: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  15: rustfmt_nightly::visitor::FmtVisitor::visit_block
  16: rustfmt_nightly::expr::rewrite_block_with_visitor
  17: rustfmt_nightly::expr::format_expr
  18: <rustfmt_nightly::expr::ArmWrapper<'a> as rustfmt_nightly::rewrite::Rewrite>::rewrite
  19: <rustfmt_nightly::lists::ListItems<'a, I, F1, F2, F3> as core::iter::iterator::Iterator>::next
  20: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  21: rustfmt_nightly::expr::format_expr
  22: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Stmt>::rewrite
  23: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  24: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  25: rustfmt_nightly::visitor::FmtVisitor::visit_block
  26: rustfmt_nightly::visitor::FmtVisitor::visit_fn
  27: rustfmt_nightly::visitor::FmtVisitor::visit_item
  28: rustfmt_nightly::visitor::FmtVisitor::walk_items
  29: rustfmt_nightly::visitor::FmtVisitor::walk_mod_items
  30: rustfmt_nightly::visitor::FmtVisitor::visit_item
  31: rustfmt_nightly::visitor::FmtVisitor::walk_items
  32: rustfmt_nightly::run
  33: rustfmt::execute
  34: rustfmt::main
  35: std::rt::lang_start::{{closure}}
  36: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  37: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  38: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  39: main
  40: __libc_start_main
  41: _start
```

**Comment by topecongiro** [comment]
Closing as a dup of #2370.
