### ISSUE TITLE
rustfmt panic in version 0.3.7

### ISSUE THREAD

**Issue by tspiteri** [rust-lang-nursery/rustfmt#2403]
```
$ rustfmt -V
0.3.7-nightly ( )

$ rustc +nightly -V
rustc 1.25.0-nightly (8ccab7eed 2018-01-31)

$ echo "mod a;" | RUST_BACKTRACE=1 rustfmt
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic
             at libcore/panicking.rs:51
  10: <syntax::codemap::CodeMap as rustfmt_nightly::codemap::SpanUtils>::span_after
  11: rustfmt_nightly::visitor::FmtVisitor::visit_item
  12: rustfmt_nightly::visitor::FmtVisitor::walk_items
  13: rustfmt_nightly::run
  14: rustfmt::execute
  15: rustfmt::main
  16: std::rt::lang_start::{{closure}}
  17: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  18: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  19: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  20: main
  21: __libc_start_main
  22: _start
```

**Comment by nrc** [comment]
I've seen this bug via the RLS tests, but I can't seem to repro using rustfmt. This should give a parsing error (because of a missing a.rs)

**Comment by tspiteri** [comment]
For what it's worth, the commit that causes this is 56c6d73d. And #2406 fixes it for me.

```
$ git checkout 56c6d73d^
Previous HEAD position was 2a71bef0... 0.3.7
HEAD is now at e0e3e222... 0.3.6

$ echo "mod a;" | RUST_BACKTRACE=1 cargo +nightly run --bin rustfmt
   Compiling rustfmt-nightly v0.3.6 (file:///.../rustfmt)
    Finished dev [unoptimized + debuginfo] target(s) in 22.59 secs
     Running `target/debug/rustfmt`
mod a;

$ git checkout 56c6d73d
Previous HEAD position was e0e3e222... 0.3.6
HEAD is now at 56c6d73d... Reorder modules

$ echo "mod a;" | RUST_BACKTRACE=1 cargo +nightly run --bin rustfmt
   Compiling rustfmt-nightly v0.3.6 (file:///.../rustfmt)
    Finished dev [unoptimized + debuginfo] target(s) in 23.23 secs
     Running `target/debug/rustfmt`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic
             at libcore/panicking.rs:51
  10: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:20
  11: <syntax::codemap::CodeMap as rustfmt_nightly::codemap::SpanUtils>::span_after
             at src/codemap.rs:52
  12: rustfmt_nightly::visitor::FmtVisitor::format_mod
             at src/visitor.rs:756
  13: rustfmt_nightly::visitor::FmtVisitor::visit_item
             at src/visitor.rs:416
  14: rustfmt_nightly::visitor::FmtVisitor::walk_items
             at src/visitor.rs:693
  15: rustfmt_nightly::visitor::FmtVisitor::walk_mod_items
             at src/visitor.rs:699
  16: rustfmt_nightly::visitor::FmtVisitor::format_separate_mod
             at src/visitor.rs:779
  17: rustfmt_nightly::format_ast
             at src/lib.rs:343
  18: rustfmt_nightly::format_input
             at src/lib.rs:648
  19: rustfmt_nightly::run
             at src/lib.rs:706
  20: rustfmt::execute
             at src/bin/rustfmt.rs:256
  21: rustfmt::main
             at src/bin/rustfmt.rs:342
  22: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  23: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  24: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  25: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  26: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  27: main
  28: __libc_start_main
  29: _start

$ git checkout nrc/str-fix
Previous HEAD position was 56c6d73d... Reorder modules
HEAD is now at 30a28a26... Make `is_mod_decl` more accommodating

$ echo "mod a;" | RUST_BACKTRACE=1 cargo +nightly run --bin rustfmt
   Compiling rustfmt-nightly v0.3.8 (file:///tmp/rustfmt)
    Finished dev [unoptimized + debuginfo] target(s) in 8.37 secs
     Running `target/debug/rustfmt`
mod a;
```
