### ISSUE TITLE
rustfmt panics on innocent-looking macro_rules!

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rustfmt#2466]
The following `macro_rules!` will crash rustfmt from the master branch:
```rust
macro_rules! t (
    () => ()
);
```

#### Backtrace
```
thread 'main' panicked at 'Bad offset', libcore/option.rs:917:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:400
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:347
   6: rust_begin_unwind
             at libstd/panicking.rs:323
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::option::expect_failed
             at libcore/option.rs:917
   9: <rustfmt_core::visitor::SnippetProvider<'a> as rustfmt_core::codemap::SpanUtils>::span_after
  10: rustfmt_core::macros::rewrite_macro_def
  11: rustfmt_core::visitor::FmtVisitor::visit_item
  12: rustfmt_core::reorder::<impl rustfmt_core::visitor::FmtVisitor<'a>>::visit_items_with_reordering
  13: rustfmt_core::run
  14: rustfmt::execute
  15: rustfmt::main
  16: std::rt::lang_start::{{closure}}
  17: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:305
  18: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  19: std::rt::lang_start_internal
             at libstd/panicking.rs:284
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  20: main
  21: __libc_start_main
  22: _start
```

**Comment by topecongiro** [comment]
rustfmt will not crash if the `macro_rules!` uses `{}` over `();`:
```rust
macro_rules! t {
    () => ()
}
```
