### ISSUE TITLE
Panic when running on gnome-class

### ISSUE THREAD

**Issue by federicomenaquintero** [rust-lang-nursery/rustfmt#2615]
Rustfmt panics when run on [gnome-class](https://gitlab.gnome.org/federico/gnome-class).  Currently we have an `ignore` section in the `.rustfmt.toml` in there; this avoids the problematic files.  If one removes any of the files in the `ignore` section, then `cargo fmt` will panic.

```
[rust] tlacoyo:~/src/gnome-class (master *)$ RUST_BACKTRACE=1 cargo fmt
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:400
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:347
   6: rust_begin_unwind
             at libstd/panicking.rs:323
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::panicking::panic
             at libcore/panicking.rs:51
   9: <rustfmt_nightly::lists::ListItems<'a, I, F1, F2, F3> as core::iter::iterator::Iterator>::next
  10: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  11: <rustfmt_nightly::overflow::Context<'a, T>>::rewrite_items
  12: <rustfmt_nightly::overflow::Context<'a, T>>::rewrite
  13: rustfmt_nightly::overflow::rewrite_with_parens
  14: rustfmt_nightly::macros::rewrite_macro_inner
  15: rustfmt_nightly::types::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Ty>::rewrite
  16: <rustfmt_nightly::types::SegmentParam<'a> as rustfmt_nightly::rewrite::Rewrite>::rewrite
  17: <rustfmt_nightly::overflow::Context<'a, T>>::rewrite_items
  18: <rustfmt_nightly::overflow::Context<'a, T>>::rewrite
  19: rustfmt_nightly::overflow::rewrite_with_angle_brackets
  20: rustfmt_nightly::types::rewrite_segment
  21: rustfmt_nightly::types::rewrite_path
  22: rustfmt_nightly::types::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Ty>::rewrite
  23: rustfmt_nightly::items::rewrite_struct_field
  24: <rustfmt_nightly::lists::ListItems<'a, I, F1, F2, F3> as core::iter::iterator::Iterator>::next
  25: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  26: rustfmt_nightly::vertical::rewrite_with_alignment
  27: rustfmt_nightly::items::format_struct
  28: rustfmt_nightly::items::<impl rustfmt_nightly::visitor::FmtVisitor<'a>>::visit_struct
  29: rustfmt_nightly::visitor::FmtVisitor::visit_item
  30: rustfmt_nightly::reorder::<impl rustfmt_nightly::visitor::FmtVisitor<'a>>::visit_items_with_reordering
  31: rustfmt_nightly::visitor::FmtVisitor::walk_mod_items
  32: rustfmt_nightly::visitor::FmtVisitor::format_separate_mod
  33: rustfmt_nightly::format_input_inner
  34: syntax::with_globals
  35: rustfmt_nightly::run
  36: rustfmt::execute
  37: rustfmt::main
```

Here's [the downstream bug for this](https://gitlab.gnome.org/federico/gnome-class/issues/19).

**Comment by topecongiro** [comment]
This looks like a related issue to https://github.com/rust-lang-nursery/rustfmt/issues/2569. Would you mind updating your nightly toolchain and update rustfmt to the latest version (`rustfmt 0.4.1-nightly (e784712f 2018-04-09)`)? I think that the issue is fixed with it.

**Comment by federicomenaquintero** [comment]
Indeed it is fixed with that.  Thank you!

**Comment by iddm** [comment]
In every single project I try to run cargo fmt now:

```
RUST_BACKTRACE=1 cargo fmt
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic
             at libcore/panicking.rs:51
  10: <cargo_metadata::WorkspaceMember as serde::de::Deserialize<'de>>::deserialize
  11: <&'a mut serde_json::de::Deserializer<R> as serde::de::Deserializer<'de>>::deserialize_seq
  12: <&'a mut serde_json::de::Deserializer<R> as serde::de::Deserializer<'de>>::deserialize_struct
```
Another stack trace:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic
             at libcore/panicking.rs:51
  10: <cargo_metadata::WorkspaceMember as serde::de::Deserialize<'de>>::deserialize
  11: <&'a mut serde_json::de::Deserializer<R> as serde::de::Deserializer<'de>>::deserialize_seq
  12: <&'a mut serde_json::de::Deserializer<R> as serde::de::Deserializer<'de>>::deserialize_struct
  13: serde_json::de::from_str
  14: cargo_metadata::metadata_deps
  15: cargo_metadata::metadata
  16: cargo_fmt::main
  17: std::rt::lang_start::{{closure}}
  18: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  19: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  20: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  21: main
  22: <unknown>
  23: __libc_start_main
  24: _start
  ```

It has been so for a month or more.

```
rustc --version
rustc 1.78.0 (9b00956e5 2024-04-29)
```

**Comment by calebcartwright** [comment]
@iddm thanks for trying to see if there was an existing issue that represented the situation you were experiencing, but this one seems unrelated and is exceptionally old. Please open a new issue with a complete and minimal reproducible example
