### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21

### ISSUE THREAD

**Issue by haraldh** [rust-lang-nursery/rustfmt#2782]
```
$ RUST_BACKTRACE=1 cargo +nightly fmt  --version
rustfmt 0.8.2-nightly (08da30d 2018-06-06)

$ cat ~/rustfmt-backtrace.rs
fn f(){{let f={let f={{match f{F(f,_)=>{{loop{let f={match f{F(f,_)=>{{match f{F(f,_)=>{{loop{let f={let f={match f{'-'=>F(f,()),}};};}}}}}}}};}}}}}};};}}

$ cargo +nightly fmt  --all
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.

$ RUST_BACKTRACE=1 cargo +nightly fmt  --all
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::panicking::panic
             at libcore/panicking.rs:53
   9: <rustfmt_nightly::overflow::Context<'a, T>>::new
  10: <rustfmt_nightly::overflow::Context<'a, T>>::new
  11: rustfmt_nightly::expr::format_expr
  12: <rustfmt_nightly::overflow::Context<'a, T>>::rewrite
  13: rustfmt_nightly::expr::rewrite_call
  14: rustfmt_nightly::expr::format_expr
  15: <rustfmt_nightly::matches::ArmWrapper<'a> as rustfmt_nightly::rewrite::Rewrite>::rewrite
  16: <rustfmt_nightly::lists::ListItems<'a, I, F1, F2, F3> as core::iter::iterator::Iterator>::next
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  18: rustfmt_nightly::matches::rewrite_match
  19: rustfmt_nightly::expr::format_expr
  20: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Stmt>::rewrite
  21: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  22: rustfmt_nightly::visitor::FmtVisitor::visit_block
  23: rustfmt_nightly::expr::rewrite_block_with_visitor
  24: rustfmt_nightly::expr::rewrite_block
  25: rustfmt_nightly::expr::format_expr
  26: rustfmt_nightly::expr::rewrite_assign_rhs
  27: rustfmt_nightly::items::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Local>::rewrite
  28: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Stmt>::rewrite
  29: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  30: rustfmt_nightly::visitor::FmtVisitor::visit_block
  31: rustfmt_nightly::expr::rewrite_block_with_visitor
  32: rustfmt_nightly::expr::rewrite_block
  33: rustfmt_nightly::expr::format_expr
  34: rustfmt_nightly::expr::rewrite_assign_rhs
  35: rustfmt_nightly::items::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Local>::rewrite
  36: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Stmt>::rewrite
  37: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  38: rustfmt_nightly::visitor::FmtVisitor::visit_block
  39: rustfmt_nightly::expr::rewrite_block_with_visitor
  40: <rustfmt_nightly::expr::ControlFlow<'a> as rustfmt_nightly::rewrite::Rewrite>::rewrite
  41: rustfmt_nightly::expr::format_expr
  42: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Stmt>::rewrite
  43: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  44: rustfmt_nightly::visitor::FmtVisitor::visit_block
  45: rustfmt_nightly::expr::rewrite_block_with_visitor
  46: rustfmt_nightly::expr::format_expr
  47: <rustfmt_nightly::matches::ArmWrapper<'a> as rustfmt_nightly::rewrite::Rewrite>::rewrite
  48: <rustfmt_nightly::lists::ListItems<'a, I, F1, F2, F3> as core::iter::iterator::Iterator>::next
  49: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  50: rustfmt_nightly::matches::rewrite_match
  51: rustfmt_nightly::expr::format_expr
  52: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Stmt>::rewrite
  53: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  54: rustfmt_nightly::visitor::FmtVisitor::visit_block
  55: rustfmt_nightly::expr::rewrite_block_with_visitor
  56: rustfmt_nightly::expr::format_expr
  57: <rustfmt_nightly::matches::ArmWrapper<'a> as rustfmt_nightly::rewrite::Rewrite>::rewrite
  58: <rustfmt_nightly::lists::ListItems<'a, I, F1, F2, F3> as core::iter::iterator::Iterator>::next
  59: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  60: rustfmt_nightly::matches::rewrite_match
  61: rustfmt_nightly::expr::format_expr
  62: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Stmt>::rewrite
  63: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  64: rustfmt_nightly::visitor::FmtVisitor::visit_block
  65: rustfmt_nightly::expr::rewrite_block_with_visitor
  66: rustfmt_nightly::expr::rewrite_block
  67: rustfmt_nightly::expr::format_expr
  68: rustfmt_nightly::expr::rewrite_assign_rhs
  69: rustfmt_nightly::items::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Local>::rewrite
  70: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Stmt>::rewrite
  71: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  72: rustfmt_nightly::visitor::FmtVisitor::visit_block
  73: rustfmt_nightly::expr::rewrite_block_with_visitor
  74: <rustfmt_nightly::expr::ControlFlow<'a> as rustfmt_nightly::rewrite::Rewrite>::rewrite
  75: rustfmt_nightly::expr::format_expr
  76: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Stmt>::rewrite
  77: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  78: rustfmt_nightly::visitor::FmtVisitor::visit_block
  79: rustfmt_nightly::expr::rewrite_block_with_visitor
  80: rustfmt_nightly::expr::format_expr
  81: <rustfmt_nightly::matches::ArmWrapper<'a> as rustfmt_nightly::rewrite::Rewrite>::rewrite
  82: <rustfmt_nightly::lists::ListItems<'a, I, F1, F2, F3> as core::iter::iterator::Iterator>::next
  83: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  84: rustfmt_nightly::matches::rewrite_match
  85: rustfmt_nightly::expr::format_expr
  86: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Stmt>::rewrite
  87: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  88: rustfmt_nightly::visitor::FmtVisitor::visit_block
  89: rustfmt_nightly::expr::rewrite_block_with_visitor
  90: rustfmt_nightly::expr::format_expr
  91: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Stmt>::rewrite
  92: rustfmt_nightly::visitor::FmtVisitor::walk_stmts
  93: rustfmt_nightly::visitor::FmtVisitor::visit_block
  94: rustfmt_nightly::expr::rewrite_block_with_visitor
  95: rustfmt_nightly::expr::rewrite_block
  96: rustfmt_nightly::expr::format_expr
  97: rustfmt_nightly::expr::rewrite_assign_rhs
  98: rustfmt_nightly::items::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Local>::rewrite
  99: rustfmt_nightly::expr::<impl rustfmt_nightly::rewrite::Rewrite for syntax::ast::Stmt>::rewrite

```

**Comment by TNkemdilim** [comment]
I'm also experiencing this same issue.
