### ISSUE TITLE
panic when formatting multiline comment

### ISSUE THREAD

**Issue by Naddiseo** [rust-lang-nursery/rustfmt#3132]
```
$ rustfmt -V
rustfmt 0.99.6-nightly ( )
$ cat src/test_case.rs 
fn test() {
    /*
    a
	*/
}

$ RUST_BACKTRACE=1 RUST_LOG=rustfmt=DEBUG rustfmt src/test_case.rs 
DEBUG 2018-10-24T23:55:09Z: rustfmt_nightly::modules: list_submodules: search_dir: "/xxx/src"
DEBUG 2018-10-24T23:55:09Z: rustfmt_nightly::items: compute_budgets_for_args 7 Indent { block_indent: 0, alignment: 0 }, 0, false
DEBUG 2018-10-24T23:55:09Z: rustfmt_nightly::items: rewrite_fn_base: one_line_budget: 89, multi_line_budget: 95, arg_indent: Indent { block_indent: 4, alignment: 0 }
DEBUG 2018-10-24T23:55:09Z: rustfmt_nightly::items: rewrite_args: budget: 89, tactic: Horizontal
DEBUG 2018-10-24T23:55:09Z: rustfmt_nightly::visitor: visit_block: Loc { file: SourceFile(/xxx/src/test_case.rs), line: 1, col: CharPos(10), col_display: 10 } Loc { file: SourceFile(/xxx/src/test_case.rs), line: 5, col: CharPos(1), col_display: 1 }
DEBUG 2018-10-24T23:55:09Z: rustfmt_nightly::missed_spans: write_snippet `
    /*
    a
	*/
`
DEBUG 2018-10-24T23:55:09Z: rustfmt_nightly::missed_spans: Normal: "\n    "
DEBUG 2018-10-24T23:55:09Z: rustfmt_nightly::missed_spans: Comment: "/*\n    a\n\t*/"
thread 'main' panicked at 'byte index 4 is out of bounds of `	*/`', libcore/str/mod.rs:2094:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::str::slice_error_fail
             at libcore/str/mod.rs:0
   9: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}
  10: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeFrom<usize>>::index::{{closure}}
  11: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  12: rustfmt_nightly::comment::identify_comment
  13: rustfmt_nightly::missed_spans::<impl rustfmt_nightly::visitor::FmtVisitor<'a>>::process_comment
  14: rustfmt_nightly::missed_spans::<impl rustfmt_nightly::visitor::FmtVisitor<'a>>::format_missing_with_indent
  15: rustfmt_nightly::visitor::FmtVisitor::visit_block
  16: rustfmt_nightly::visitor::FmtVisitor::visit_fn
  17: rustfmt_nightly::visitor::FmtVisitor::visit_item
  18: rustfmt_nightly::reorder::<impl rustfmt_nightly::visitor::FmtVisitor<'a>>::visit_items_with_reordering
  19: rustfmt_nightly::visitor::FmtVisitor::walk_mod_items
  20: rustfmt_nightly::visitor::FmtVisitor::format_separate_mod
  21: rustfmt_nightly::formatting::format_project
  22: <scoped_tls::ScopedKey<T>>::set
  23: syntax::with_globals
  24: rustfmt::format_and_emit_report
  25: <rustfmt_nightly::Session<'b, T>>::override_config
  26: rustfmt::execute
  27: rustfmt::main
  28: std::rt::lang_start::{{closure}}
  29: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  30: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  31: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  32: main
  33: __libc_start_main
  34: _start


```

>

**Comment by scampi** [comment]
if nobody's on that, i'd take a look at it
