### ISSUE TITLE
Panic on invalid syntax (empty struct literal)

### ISSUE THREAD

**Issue by justinas** [rust-lang-nursery/rustfmt#835]
Using this snippet:
```rust
struct MyStruct {
    field: (),
}

fn main() {
    MyStruct {};
}
```

`rustfmt a.rs` panics:
```
thread '<main>' panicked at 'assertion failed: !fields.is_empty() || base.is_some()', /Users/justinas/.multirust/toolchains/1.6.0/cargo/registry/src/github.com-88ac128001ac3a9a/rustfmt-0.3.0/src/expr.rs:1392
```

... instead of reporting the error that rustc produces:

```
a.rs:6:5: 6:16 error: missing field: `field` [E0063]
a.rs:6     MyStruct {};
           ^~~~~~~~~~~
a.rs:6:5: 6:16 help: run `rustc --explain E0063` to see a detailed explanation
error: aborting due to previous error
```

**Comment by jgillich** [comment]
Seeing the same, but for completely valid and compiling code:
```
thread '<main>' panicked at 'assertion failed: !fields.is_empty() || base.is_some()', /home/jakob/.cargo/registry/src/github.com-88ac128001ac3a9a/rustfmt-0.3.0/src/expr.rs:1392
```

**Comment by marcusklaas** [comment]
@jgillich Could you provide an example snippet?

**Comment by leeola** [comment]
Experiencing the same issue. @marcusklaas What type of snippet are you looking for?

```
struct MyStruct {
}

fn main() {
    MyStruct {};
}
```

also triggers the panic

**Comment by marcusklaas** [comment]
Yea, was looking for a snippet which compiles yet makes rustfmt panic. Thanks!
