### ISSUE TITLE
panicked at 'Box<Any>' ... syntex_syntax-0.30.0/src/parse/lexer/mod.rs:1438

### ISSUE THREAD

**Issue by respeccing** [rust-lang-nursery/rustfmt#899]
```bash
$ echo '`'|RUST_BACKTRACE=1 ./rustfmt
stdin:1:1: 1:2 error: unknown start of token: `
stdin:1 `
        ^
thread '<main>' panicked at 'Box<Any>', /home/zazdxscf/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.30.0/src/parse/lexer/mod.rs:1438
stack backtrace:
   1:     0x55b3ed5af0b0 - std::sys::backtrace::tracing::imp::write::h3152d690c5b90b0c
   2:     0x55b3ed5b1bfb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hb638acea7c29901b
   3:     0x55b3ed5b1882 - std::panicking::default_hook::h508c3dab3df347d6
   4:     0x55b3ed5a30ef - std::sys_common::unwind::begin_unwind_inner::h5cd31b1580026517
   5:     0x55b3ed29bba6 - std::sys_common::unwind::begin_unwind::h8a2d02a56698e83a
                        at src/libstd/sys/common/unwind/mod.rs:219
   6:     0x55b3ed3ee484 - syntex_syntax::parse::lexer::StringReader::next_token_inner::he61f3e2291c514c3
                        at /home/zazdxscf/build/1nonpkgs/rustfmt/<std macros>:3
   7:     0x55b3ed3e76ef - syntex_syntax::parse::lexer::StringReader::advance_token::h255aae7847b19b40
                        at /home/zazdxscf/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.30.0/src/parse/lexer/mod.rs:266
   8:     0x55b3ed31adf1 - syntex_syntax::parse::lexer::StringReader::new::hef772bb54d9273a0
                        at /home/zazdxscf/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.30.0/src/parse/lexer/mod.rs:165
   9:     0x55b3ed31a8a9 - syntex_syntax::parse::filemap_to_tts::h2ae43363a6ee1352
                        at /home/zazdxscf/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.30.0/src/parse/mod.rs:255
  10:     0x55b3ed319a87 - syntex_syntax::parse::filemap_to_parser::hd88d027ff0326706
                        at /home/zazdxscf/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.30.0/src/parse/mod.rs:213
  11:     0x55b3ed318445 - syntex_syntax::parse::new_parser_from_source_str::h82e7cca3e8c9d718
                        at /home/zazdxscf/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.30.0/src/parse/mod.rs:182
  12:     0x55b3ed3181f4 - syntex_syntax::parse::parse_crate_from_source_str::hc65dcebb0b4dcf4a
                        at /home/zazdxscf/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.30.0/src/parse/mod.rs:95
  13:     0x55b3ed093473 - rustfmt::format_string::h2082095943e74a1c
                        at src/lib.rs:381
  14:     0x55b3ed0b1b3b - rustfmt::run_from_stdin::h1e8135c29ff2a697
                        at src/lib.rs:445
  15:     0x55b3ed0512b6 - rustfmt::execute::h9c9253d20e08b170
                        at src/bin/rustfmt.rs:200
  16:     0x55b3ed0633cc - rustfmt::main::h72bee7f7a14fa8c0
                        at src/bin/rustfmt.rs:245
  17:     0x55b3ed5b14b4 - std::sys_common::unwind::try::try_fn::h48f26a76fbfde40e
  18:     0x55b3ed5ae51b - __rust_try
  19:     0x55b3ed5b0efb - std::rt::lang_start::h7bd5d5e5d238827f
  20:     0x55b3ed064b69 - main
  21:     0x7f83fcd9659f - __libc_start_main
  22:     0x55b3ed04b768 - _start
  23:                0x0 - <unknown>
```

rustfmt commit used: d9ccec6f82fb4d58e41b78de6be530de72e4db00

$ rustc -Vv
!! executing '/home/zazdxscf/build/1nonpkgs/rust/rust//x86_64-unknown-linux-gnu/stage2/bin//rustc' with args: '-Vv'
rustc 1.9.0-dev (f2285bdaf 2016-04-02)
binary: rustc
commit-hash: f2285bdaf57e9cb56120902ae4b3b0a26d761f31
commit-date: 2016-04-02
host: x86_64-unknown-linux-gnu
release: 1.9.0-dev

**Comment by respeccing** [comment]
Related or same? #753

**Comment by marcusklaas** [comment]
Seems like a specific instance of #753 indeed. Closing.

Note that https://github.com/rust-lang-nursery/rustfmt/blob/master/Design.md states that formatting non-compiling code is a very low priority issue for now.
