### ISSUE TITLE
Panic when macro has doc comment argument

### ISSUE THREAD

**Issue by cmbrandenburg** [rust-lang-nursery/rustfmt#917]
Here's a program that causes `rustfmt` (v0.4) to panic:

``` rust
macro_rules! define_something {
    ($type_name:ident, #[$description:meta]) => {
        /// This represents a
        #[$description]
        /// that does blah blah blah.
        pub struct $type_name {
            _phantom: std::marker::PhantomData<()>,
        }
    }
}

define_something!(Foo, /** foo-thing */);

fn main() {
}
```

This kind of macro worked with `rustfmt` v0.3.

Here's the backtrace:

```
thread '<main>' panicked at 'explicit panic', /home/craig/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.30.0/src/errors/mod.rs:360
stack backtrace:
   1:     0x7f04b5c74220 - sys::backtrace::tracing::imp::write::hf7e21f48f7cb711bEju
   2:     0x7f04b5c76795 - panicking::default_handler::_<closure>::closure.42502
   3:     0x7f04b5c7623f - panicking::default_handler::hac4d0be12e3129d2Gwy
   4:     0x7f04b5c67ef6 - sys_common::unwind::begin_unwind_inner::hf13a3e016c1e78e1bct
   5:     0x7f04b59012e7 - sys_common::unwind::begin_unwind::h2616575216763365083
                        at ../src/libstd/sys/common/unwind/mod.rs:227
   6:     0x7f04b5916a6a - errors::DiagnosticBuilder<'a>.Drop::drop::hd72ad825f3e530645Ed
                        at /home/craig/art/rustfmt/<std macros>:3
   7:     0x7f04b574cd5c - syntax..errors..DiagnosticBuilder::drop.23354::h25602577c29d5f8d
   8:     0x7f04b58eb716 - core..result..Result<syntax..ptr..P<syntax..ast..Expr>, syntax..errors..DiagnosticBuilder>::drop.29930::h04e9c3c0ad27d039
   9:     0x7f04b57ce330 - macros::rewrite_macro::h683530a5fa37a240dno
                        at src/macros.rs:83
  10:     0x7f04b57be761 - visitor::FmtVisitor<'a>::visit_mac::h668550e50e5ac2df5Of
                        at src/visitor.rs:390
  11:     0x7f04b57bd50e - visitor::FmtVisitor<'a>::visit_item::hafde62ea9b31d7belEf
                        at src/visitor.rs:256
  12:     0x7f04b57d28a3 - visitor::FmtVisitor<'a>::walk_mod_items::h7a7428ee1356ac90STf
                        at src/visitor.rs:460
  13:     0x7f04b57279ae - visitor::FmtVisitor<'a>::format_separate_mod::h5ae0d4856f87fed2HWf
                        at src/visitor.rs:499
  14:     0x7f04b5724570 - fmt_ast::h11ec60f69209ee0dIZo
                        at src/lib.rs:281
  15:     0x7f04b57507e2 - format::h69a33b3cbc35198aA8o
                        at src/lib.rs:422
  16:     0x7f04b5750ac3 - run::h4ba396162e16379119o
                        at src/lib.rs:432
  17:     0x7f04b56dfe90 - execute::hf0c687af362492387ga
                        at src/bin/rustfmt.rs:236
  18:     0x7f04b56f2e49 - main::hf1be1d729aa9052fmpa
                        at src/bin/rustfmt.rs:245
  19:     0x7f04b5c75ec4 - sys_common::unwind::try::try_fn::h9896872240422604242
  20:     0x7f04b5c737f8 - __rust_try
  21:     0x7f04b5c75b50 - rt::lang_start::h0d9dcd8707a91319Uoy
  22:     0x7f04b56f43c9 - main
  23:     0x7f04b4abcb44 - __libc_start_main
  24:     0x7f04b56d82f8 - <unknown>
  25:                0x0 - <unknown>
```

**Comment by Zarokka** [comment]
This exact snippet does not crash in master or 0.6.2.
Also no crash when cargo-fmt is run on the https://github.com/chill-rs/chill master branch.

Probably fixed (or the snippet is not quite enough to reproduce it)

**Comment by nrc** [comment]
@cmbrandenburg can you confirm that this is fixed please?
